from pathlib import Path
APPEARANCES_OUTFILE = "detecciones.txt"
DATA_FOLDER = Path("data/")

# FEATURE EXTRACTION
SAMPLES_PER_SECOND = 1
SOBEL_THRESH = 150
SAMPLING_DIMENSIONS = (32, 32)
CACHE_FOLDER = Path("cache/")

# KNN
K = 5
# EXTRA
SUPPORTED_EXTENSIONS = ["mpg", "mp4"]

# AD DETECTION
SCORE_THRESHOLD = 0.4
