from pathlib import Path
# GENERAL
DATA_FOLDER = Path("data/")
CACHE_FOLDER = Path("cache/")
SUPPORTED_EXTENSIONS = ["mpg", "mp4"]

# FEATURE EXTRACTION
SAMPLES_PER_SECOND = 2
SOBEL_THRESH = 100
SAMPLING_DIMENSIONS = (32, 32)

# KNN
K = 5

# AD DETECTION
APPEARANCES_OUTFILE = "detecciones.txt"
SCORE_THRESHOLD = 0.25
